language: ruby
rvm:
  - 2.7.7
  - 3.0.5
  - 3.1.3
  - 3.2.1

before_install:
  - gem update bundler && bundle --version

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile

matrix:
  exclude:
    - rvm: rbx
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/3.2.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/4.1.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/4.2.gemfile
  include:
    - rvm: 2.2.6
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/5.0.gemfile
