language: ruby
rvm:
  # - 1.9.3
  # - 2.0.0-p648
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - jruby-19mode # JRuby in 1.9 mode
  # - rbx-2

before_install:
  - gem update bundler && bundle --version

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
  - gemfiles/6.1.gemfile
  - gemfiles/7.0.gemfile
  - gemfiles/7.1.gemfile

script: bundle exec rspec

matrix:
  exclude:
    # Rails 3.2
    - rvm: jruby-19mode
      gemfile: gemfiles/3.2.gemfile
    - rvm: 2.5
      gemfile: gemfiles/3.2.gemfile
    - rvm: 2.7
      gemfile: gemfiles/3.2.gemfile
    - rvm: 3.0
      gemfile: gemfiles/3.2.gemfile
    - rvm: 3.1
      gemfile: gemfiles/3.2.gemfile
    - rvm: 3.2
      gemfile: gemfiles/3.2.gemfile
    - rvm: 3.3
      gemfile: gemfiles/3.2.gemfile

    # Rails 4.0
    - rvm: jruby-19mode
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.7
      gemfile: gemfiles/4.0.gemfile
    - rvm: 3.0
      gemfile: gemfiles/4.0.gemfile
    - rvm: 3.1
      gemfile: gemfiles/4.0.gemfile
    - rvm: 3.2
      gemfile: gemfiles/4.0.gemfile
    - rvm: 3.3
      gemfile: gemfiles/4.0.gemfile

    # Rails 4.1
    - rvm: jruby-19mode
      gemfile: gemfiles/4.1.gemfile
    - rvm: 2.7
      gemfile: gemfiles/4.1.gemfile
    - rvm: 3.0
      gemfile: gemfiles/4.1.gemfile
    - rvm: 3.1
      gemfile: gemfiles/4.1.gemfile
    - rvm: 3.2
      gemfile: gemfiles/4.1.gemfile
    - rvm: 3.3
      gemfile: gemfiles/4.1.gemfile

    # Rails 4.2
    - rvm: jruby-19mode
      gemfile: gemfiles/4.2.gemfile
    - rvm: 2.7
      gemfile: gemfiles/4.2.gemfile
    - rvm: 3.0
      gemfile: gemfiles/4.2.gemfile
    - rvm: 3.1
      gemfile: gemfiles/4.2.gemfile
    - rvm: 3.2
      gemfile: gemfiles/4.2.gemfile
    - rvm: 3.3
      gemfile: gemfiles/4.2.gemfile

    # Rails 5.0
    - rvm: jruby-19mode
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/5.0.gemfile
    - rvm: 3.0
      gemfile: gemfiles/5.0.gemfile

    # Rails 5.1
    - rvm: jruby-19mode
      gemfile: gemfiles/5.1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/5.1.gemfile
    - rvm: 3.0
      gemfile: gemfiles/5.1.gemfile

    # Rails 5.2
    - rvm: jruby-19mode
      gemfile: gemfiles/5.2.gemfile
    - rvm: 2.1
      gemfile: gemfiles/5.2.gemfile
    - rvm: 3.0
      gemfile: gemfiles/5.2.gemfile

    # Rails 6.0
    - rvm: jruby-19mode
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.3
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/6.0.gemfile
    - rvm: 3.0
      gemfile: gemfiles/6.0.gemfile

    # Rails 6.1
    - rvm: jruby-19mode
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.2
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.3
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.4
      gemfile: gemfiles/6.1.gemfile
    - rvm: 3.0
      gemfile: gemfiles/6.1.gemfile

    # Rails 7.0
    - rvm: jruby-19mode
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.3
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.5
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.6
      gemfile: gemfiles/7.0.gemfile
    - rvm: 3.0
      gemfile: gemfiles/7.0.gemfile

    # Rails 7.1
    - rvm: jruby-19mode
      gemfile: gemfiles/7.1.gemfile
    - rvm: 2.1
      gemfile: gemfiles/7.1.gemfile
    - rvm: 2.2
      gemfile: gemfiles/7.1.gemfile
    - rvm: 2.3
      gemfile: gemfiles/7.1.gemfile
    - rvm: 2.4
      gemfile: gemfiles/7.1.gemfile
    - rvm: 2.5
      gemfile: gemfiles/7.1.gemfile
    - rvm: 2.6
      gemfile: gemfiles/7.1.gemfile
    - rvm: 3.0
      gemfile: gemfiles/7.1.gemfile
