language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.7.0
  - 3.0.0
  - 3.1.0
  - jruby-19mode # JRuby in 1.9 mode
  # - rbx-2

before_install:
  - gem update bundler && bundle --version

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/6.0.gemfile
  - gemfiles/6.1.gemfile
  - gemfiles/7.0.gemfile

matrix:
  exclude:
    - rvm: rbx
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/3.2.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/4.1.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/4.2.gemfile
  include:
    - rvm: 2.2.6
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/5.0.gemfile

script: bundle exec rspec
