language: ruby
rvm:
  - 1.9.3
  # - 2.0.0-p648
  - 2.1.10
  - 2.2.6
  - 2.3.7
  - 2.4.10
  - 2.5.9
  - 2.6.10
  - 2.7.8
  - 3.0.7
  - 3.1.5
  # - 3.2.4
  # - 3.3.1
  - jruby-19mode # JRuby in 1.9 mode
  # - rbx-2

before_install:
  - gem update bundler && bundle --version

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/6.0.gemfile
  - gemfiles/6.1.gemfile
  # - gemfiles/7.0.gemfile
  # - gemfiles/7.1.gemfile

matrix:
  exclude:
    # Rails 3.2
    - rvm: 2.5.9
      gemfile: gemfiles/3.2.gemfile

    # Rails 4.0
    - rvm: 1.9.3
      gemfile: gemfiles/4.0.gemfile

    # Rails 4.1
    - rvm: 1.9.3
      gemfile: gemfiles/4.1.gemfile

    # Rails 4.2
    - rvm: 1.9.3
      gemfile: gemfiles/4.2.gemfile

    # Rails 5.0
    - rvm: 1.9.3
      gemfile: gemfiles/5.0.gemfile
    # - rvm: 2.0.0-p648
    #   gemfile: gemfiles/5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/5.0.gemfile


    # Rails 6.0
    - rvm: 1.9.3
      gemfile: gemfiles/6.0.gemfile
    # - rvm: 2.0.0-p648
      # gemfile: gemfiles/6.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/6.0.gemfile

    # Rails 6.1
    - rvm: 1.9.3
      gemfile: gemfiles/6.1.gemfile
    # - rvm: 2.0.0-p648
      # gemfile: gemfiles/6.1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/6.1.gemfile

    # # Rails 7.0
    # - rvm: 1.9.3
    #   gemfile: gemfiles/7.0.gemfile
    # # - rvm: 2.0.0-p648
    #   # gemfile: gemfiles/7.0.gemfile
    # - rvm: 2.1.10
    #   gemfile: gemfiles/7.0.gemfile
    # - rvm: 2.2.6
    #   gemfile: gemfiles/7.0.gemfile
    # - rvm: 2.3.7
    #   gemfile: gemfiles/7.0.gemfile
    # - rvm: 2.4.10
    #   gemfile: gemfiles/7.0.gemfile
    # - rvm: 2.5.9
    #   gemfile: gemfiles/7.0.gemfile
    # - rvm: 2.6.10
    #   gemfile: gemfiles/7.0.gemfile

    # # Rails 7.1
    # - rvm: 1.9.3
    #   gemfile: gemfiles/7.1.gemfile
    # # - rvm: 2.0.0-p648
    #   # gemfile: gemfiles/7.1.gemfile
    # - rvm: 2.1.10
    #   gemfile: gemfiles/7.1.gemfile
    # - rvm: 2.2.6
    #   gemfile: gemfiles/7.1.gemfile
    # - rvm: 2.3.7
    #   gemfile: gemfiles/7.1.gemfile
    # - rvm: 2.4.10
    #   gemfile: gemfiles/7.1.gemfile
    # - rvm: 2.5.9
    #   gemfile: gemfiles/7.1.gemfile
    # - rvm: 2.6.10
    #   gemfile: gemfiles/7.1.gemfile



script: bundle exec rspec
