language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.7
  - 2.4.10
  - 2.5.9
  - 2.6.10
  - 2.7.8
  - 3.0.7
  - 3.1.5
  - 3.2.4
  - 3.3.1
  - jruby-19mode # JRuby in 1.9 mode
  # - rbx-2

before_install:
  - gem update bundler && bundle --version

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/6.0.gemfile
  - gemfiles/6.1.gemfile
  - gemfiles/7.0.gemfile

matrix:
  exclude:
    - rvm: 2.4.10
      gemfile: gemfiles/3.2.gemfile
    - rvm: rbx
      gemfile: gemfiles/4.0.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/4.1.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/4.2.gemfile
    # rails 5.0 requires ruby >= 2.2.2
    - rvm: 1.9.3
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/5.0.gemfile
    # rails 6.0 requires ruby >= 2.5.0
    - rvm: 1.9.3
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/6.0.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/6.0.gemfile
    # rails 6.1 requires ruby >= 2.5.0
    - rvm: 1.9.3
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/6.1.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/6.1.gemfile
    # rails 7.0 requires ruby >= 2.7.0
    - rvm: 1.9.3
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.5.9
      gemfile: gemfiles/7.0.gemfile
    - rvm: 2.6.10
      gemfile: gemfiles/7.0.gemfile

script: bundle exec rspec
