services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
    platform: "linux/amd64"
    ports:
      - "3009:3000"
    volumes:
      - .:/src
    command: tail -f /dev/null
