services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
      args:
        - DOCKER_RUBY_VERSION=3.1
        - RAILS_VERSION=6.1
    platform: "linux/amd64"
    ports:
      - "3009:3000"
    volumes:
      - .:/src

    command: tail -f /dev/null
