services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
      args:
        - RUBY_VERSION=${RUBY_VERSION}
        - RAILS_VERSION=${RAILS_VERSION}
    image:
      ruby-${RUBY_VERSION}:rails-${RAILS_VERSION}
    platform: "linux/amd64"
    ports:
      - "3009:3000"
    volumes:
      - .:/src

    command: tail -f /dev/null
