services:
  app:
    env_file:
      - path: .env
        required: false
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - "linux/amd64"
      args:
        - RUBY_VERSION=${RUBY_VERSION}
        - RAILS_VERSION=${RAILS_VERSION}
    image:
      ruby-${RUBY_VERSION}-rails-${RAILS_VERSION}:latest
    platform: "linux/amd64"
    ports:
      - "3009:3000"
    volumes:
      - .:/workspaces/authority

    command: tail -f /dev/null
