version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run RSpec tests
          command: bundle exec rspec
